// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kocsma_v3;

#nullable disable

namespace kocsma_v3.Migrations
{
    [DbContext(typeof(KocsmaContext))]
    [Migration("20260304102021_kocsma")]
    partial class kocsma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("kocsma_v3.Modells.AdatokModell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Felhasznalonev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("KocsmaId")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KocsmaId");

                    b.ToTable("FelhasznaloAdatok");
                });

            modelBuilder.Entity("kocsma_v3.Modells.KocsmaModell", b =>
                {
                    b.Property<int>("KocsmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Csutortok")
                        .HasColumnType("longtext");

                    b.Property<string>("Hetfo")
                        .HasColumnType("longtext");

                    b.Property<string>("Kedd")
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pentek")
                        .HasColumnType("longtext");

                    b.Property<string>("Szerda")
                        .HasColumnType("longtext");

                    b.Property<string>("Szombat")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TulajFelhasznalo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vasarnap")
                        .HasColumnType("longtext");

                    b.HasKey("KocsmaId");

                    b.ToTable("Kocsmak");
                });

            modelBuilder.Entity("kocsma_v3.Modells.KocsmaRaktarModell", b =>
                {
                    b.Property<int>("RaktarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Ar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItalId")
                        .HasColumnType("int");

                    b.Property<int>("KocsmaId")
                        .HasColumnType("int");

                    b.Property<int>("Mennyiseg")
                        .HasColumnType("int");

                    b.HasKey("RaktarId");

                    b.HasIndex("ItalId");

                    b.HasIndex("KocsmaId");

                    b.ToTable("KocsmaRaktar");
                });

            modelBuilder.Entity("kocsma_v3.Modells.RaktarModell", b =>
                {
                    b.Property<int>("ItalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Alkoholszazalek")
                        .HasColumnType("double");

                    b.Property<decimal>("Ar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Kiszereles")
                        .HasColumnType("double");

                    b.Property<int>("Mennyiseg")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Szarmazas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ItalId");

                    b.ToTable("AlkoholosItalokRaktar");
                });

            modelBuilder.Entity("kocsma_v3.Modells.AdatokModell", b =>
                {
                    b.HasOne("kocsma_v3.Modells.KocsmaModell", "Kocsma")
                        .WithMany()
                        .HasForeignKey("KocsmaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kocsma");
                });

            modelBuilder.Entity("kocsma_v3.Modells.KocsmaRaktarModell", b =>
                {
                    b.HasOne("kocsma_v3.Modells.RaktarModell", "Ital")
                        .WithMany()
                        .HasForeignKey("ItalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kocsma_v3.Modells.KocsmaModell", "Kocsma")
                        .WithMany()
                        .HasForeignKey("KocsmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ital");

                    b.Navigation("Kocsma");
                });
#pragma warning restore 612, 618
        }
    }
}
